plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hllyoud.guess'
    compileSdk 35

    defaultConfig {
        applicationId 'com.hllyoud.guess'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '1.0.3'
    }

    buildTypes {
        debug {
            debuggable false
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
